### ISSUE TITLE
[Bug] It isn't you

### ISSUE THREAD

**Issue by arrudagates** [ConciseFunctions/its_me#1]
Because it's actually me!

**Comment by ConciseFunctions** [comment]
>:l

**Comment by arrudagates** [comment]
![cursors](https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcur.cursors-4u.net%2Ffood%2Fimages2%2Ffoo124.gif&f=1&nofb=1)

**Comment by JammSpread** [comment]
So wrong it is actually me.

**Comment by ConciseFunctions** [comment]
stap pls ;-;
